import { Container } from '@nextui-org/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Main } from '../components/Main';
import { Col, Row } from 'react-bootstrap'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Darling Happy Anniversary</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/assets/bh.png" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />
      </Head>

      <main>
        <Container>
          <div className="mt-5">
            <Row className="d-flex justify-content-center">
              <Col sm={12} className="d-flex justify-content-center">
                <h1>21  08  2022</h1>
              </Col>
              <Col sm={12}>
                <Main />
              </Col>
            </Row>
          </div>
        </Container>
      </main>

    </div>
  )
}

export default Home
